### ISSUE TITLE
Improve [array quantile] / [array random]

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#108]
I know this is on me, but I think it's important I actually understand what it is for, maybe I can make it clearer for people that, like me, are having trouble with it.

here's the text

"[array quantile] outputs the specified quantile by interpreting the array as a histogram. The output will always be in the range from 0 to "array size - 1". The 0.5 quantile is also known as the median. This generalizes the [array random] function allowing you to use the same source of randomness on several arrays, for example."

Can anyone help me with the meaning in this context of the term "histogram"? About the "median", is it really like the meadian of a list, or an array? I suspect not.

And how would you use the same source of randomness on several arrays? Maybe we can add an example for that.

**Comment by porres** [comment]
> And how would you use the same source of randomness on several arrays? Maybe we can add an example for that.

I think I get it now, like using a single random input value in different arrays at once.

**Comment by umlaeute** [comment]
yes.

`[array random]` is basically a shortcut for `[randomf]` + `[array quantile]`; with `[array quantile]` being available as a separate object, you can feed the output of a a `[randomf]` into multiple histograms.

> Can anyone help me with the meaning in this context of the term "histogram"?

it's an (approximate) distribution diagram. the help-patch shows two peaks around the index 25 and 75 and stretches of 0 around them, which means that if you use this to generate random numbers, the chance to get a value around 25 is about the same as getting a value around 75, but the chance to get a value of 50 is nil.

see https://en.wikipedia.org/wiki/Histogram

> About the "median", is it really like the meadian of a list, or an array? I suspect not.

yes, it's really the median of the popuplation that correspond to the given histogram.
In our help-patch example we have a popupation that consists of two groups, one centered around 25 and one around 75.
The [*mean* value](https://en.wikipedia.org/wiki/Arithmetic_mean) would be around 50 (the weighted average of the values; it's actually about 54.3), but because the group around 75 is larger the [*median* value](https://en.wikipedia.org/wiki/Median) is skewed to the upwards.

to calculate the quantile, you need the integral over the values of the array (which is really just the sum over its elements up to index *n*) and then look up the corresponding x value for a given (normalized) y.

So the median (which is the 50% quantile) can be looked up as 69:
![quantile](https://user-images.githubusercontent.com/214034/191430443-03feb322-e351-4ec7-b943-74c5ec151288.png)

the point here is really, that the array is a histogram of values, rather than just values.

but this is just maths. i don't think the details should be documented in the Pd-patch.

**Comment by porres** [comment]
thanks for the math class @umlaeute :)

I already had a change proposal for this help file, see attachment. I didn't change much, the text I was having trouble with is still there, but I changed the array example to a gaussian (normal distribution) one. I also changed other details of course.

Do you think this is an improvement?

![Screen Shot 2022-09-21 at 10 04 57](https://user-images.githubusercontent.com/5360142/191511729-40bf322e-159f-4c2e-8a93-8c0458d1e651.png)

**Comment by umlaeute** [comment]
i don't really have an opinion. (but i quite liked the original ad-hoc nature of the histogram; gaussian bells are what you *always* see when there's a histogram)

**Comment by porres** [comment]
I'll add an example to better explain the idea of using two [array quantile] objects with the same random source and use that 'ad hoc' table along with the bell one. I think it is important to have the normal distribution example as well. I know it's what you always see, but it can be good for those who never saw it or for those who have seen it to recognize what we're talking about.

**Comment by porres** [comment]
I added the example and created another one that shows you how to create a histogram from note inputs.

![Screen Shot 2022-09-21 at 14 41 14](https://user-images.githubusercontent.com/5360142/191573989-17ed3361-9f1b-4b50-9033-658f8363a127.png)

**Comment by umlaeute** [comment]
sidenote:
> The example below creates a histogram from a MIDI note input, or use the number box to feed it.

seems to be not proper English ("The example [...] use the number box").

(i'm of course non-native so it might work out for native speakers; but for me it sounds weird.)
