### ISSUE TITLE
"Cleaning" 4.data.structures in the doc folder (on Windows)

### ISSUE THREAD

**Issue by bazilmuzik** [pure-data/pddp#110]
There is sometimes an example that shows 2 times, e.g. 06.file.pd (which doesn't work) and 08.file.pd (which works).
It's like if there was a merging between the old documentation and the new one, instead of only the new documentation (or keeping only the old patches when nothing has changed, I don't know how things are developped here).

**Comment by Lucarda** [comment]
This mostly happened because you installed Pd without a prior uninstall of the older version.

Goto `Control Panel\All Control Panel Items\Programs and Features` and unistall Pd. (no worrries about the preferences: they wont be erased from the registry)

This will fail to clear all files since it just wipes all the files from the newer Pd. In your case ` 06.file.pd ` from the older Pd will be there.

Manually delete all the Pd folder (`C:\Program Files\pd`) (double-check there are no files you created yourself. in case there are, move them out)

install again

Done :)

**Comment by porres** [comment]
@bazilmuzik can you confirm and close this?

**Comment by bazilmuzik** [comment]
Hey, sry I have busy days, I'll test it tomorrow !

**Comment by bazilmuzik** [comment]
Ok so it worked ! In fact, I had 2 Pd folders on my computer (one in "program files" and one in "programs (x86)"), after uninstalling Pd and deleting all left files, everything were fine when I reinstalled Pd :) Case closed !
