### ISSUE TITLE
q8_sqrt~ and q8_rsqrt~ are the same as sqrt~/rsqrt~

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#125]
According to a recent discussion in the Pd-dev list. The documentation says they're different but have been the same since at least Pd 0.33!

Audio examples use the old version for no good reason and must be updated.

**Comment by porres** [comment]
For reference, the discussion in the pd-dev list https://lists.puredata.info/pipermail/pd-dev/2022-12/023162.html

**Comment by millerpuckette** [comment]
Hmm.. there must _never_ have been a real sqrt object!  Bizarre, and certainly my fault.
I think I should fix this for the next "major" release 0.54 so as not to make incompatibilities between bugfix versions.  Also can consider "fixing" the cosine table at that juncture since I'm making an incompatibility anyway :)

**Comment by porres** [comment]
What is the 'fix' you intend to make? I was assuming q8_sqrt~ is actually sqrt~ but is it the other way around? Like [sqrt~] is a cheap 8 bit one or something? :) 

If so, my documentation fix makes no sense.

**Comment by porres** [comment]
I actually get the same result from [sqrt~] and [sqrt] or even [expr sqrt($f1)]

so it doesn't seem 'broken'

**Comment by millerpuckette** [comment]
It's broken!  sqrt~ should call the true function (the q8 version is a fast approximation).  This will indeed require keeping a "compatibility" version (setting compatibility to 0.53 or earlier shold give the stupid old behavior and 0.54 onward should call a true sqrt function.

**Comment by porres** [comment]
Ok, I reverted the commit that fixed this in the documentation and will wait for this ;)

**Comment by Spacechild1** [comment]
Note that since SSE2 (= all modern processors of the last 15 years or so), squareroot and inverse squareroot are available as native CPU instructions. This means that with an optimizing compiler `sqrt()` and `1.0 / sqrt()` won't emit any calls to library functions, instead they are replaced with intrinsics and can also be nicely vectorized. It would be interesting to benchmark these against the current implementation and see if there is any speed difference left at all.

**Comment by Spacechild1** [comment]
> 0.54 onward should call a true sqrt function.

+1. Let's also not forget to add an unrolled version :-) Square root and inverse squareroot are available as vector instructions.

**Comment by porres** [comment]
I'm reopening this so it stays on my radar. I had forgotten about it.
