### ISSUE TITLE
[key] objects restrictions.

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#168]
If someone tries to use these objects to impelement a polyphonic keyboard interface for synthesis, which I think it can be a common thing, people should be warned that some hardware keyboards can't correctly handle several simultaneous keystrokes, which means you can't go crazy with polyphony. This did byte me when trying to do so and I have reported an issue on https://github.com/pure-data/pure-data/issues/2096

**Comment by umlaeute** [comment]
hmm. should we also warn people that when they are trying to use `[dac~]` to send CV to their modular synth, that "some hardware soundcards" might have a hipass built in and filter out any DC-current in the respective help-patch?

and speaking of keyboards: i'm pretty sure some MIDI-keyboards out their where you cannot press all 88 keys simultaneously (and get that data over the wire). should we add a warning to help patches of `[keyin]` and `[midiin]`?

both the keyboard and soundcard restrictions are real world problems, but they are somewhat outside the realm of Pd.
so let's not go crazy about documenting all the quirks one might encounter.

(that's not to say that I would object to a line that says that typical computer keyboards will only allow you to press a few notes simultaneously)

**Comment by porres** [comment]
While we're at it, it already mentions the caveat that  "_this only works if Pd actually gets the key events which can depend on the stacking order of windows and/or the pointer location, depending on the system._"

This is hard for me to understand. I get that Pd must be "selected", that is, the Pd application must be the front window. So, if you "select" a browser and start typing on it, Pd doesn't get key strokes, right? Isn't this always like that? Can it work differently in a particular OS? The deal with "pointer location" just has no real meaning to me, I don't get it.

**Comment by umlaeute** [comment]
yes it depends a lot on the Window Manager you are using (macOS and Windows users typically all use the same Window Manager that just enforces a given workflow; things are much different on Linux)

E.g. i have my system setup so that the mouse focus can be on a window that is not foremost (e.g. partially or (almost) completely obscured by another window). If such a window has focus than another windows (e.g. Pd) will not get any keystrokes.
usually the focused window is selected by just *moving* the mouse over the window (without clicking!), so it's very easy to switch the focus to a new (somewhat visible) window. in this case, the focus will depend on the "pointer location".

however, i can just as well (programmatically) switch to a *completely obscured* window which is not at all under my "pointer location", and still this window will receive keystrokes (and Pd will not).

**Comment by porres** [comment]
I was confused because it was clear to me it meant "mouse pointer", so I now made it clearer. I also had already mentioned that "typical computer keyboards will only allow you to press a few keys simultaneously"
