### ISSUE TITLE
html manual revision for Pd0.55

### ISSUE THREAD

**Issue by ben-wes** [pure-data/pddp#192]
@porres @Lucarda i'm creating one (hopefully last) issue for the remaining things that should be done before the release of Pd0.55 (although the current version is already releasable imho?) since the last issue's discussion escalated quite a bit.

@Lucarda: just for my understanding about the extent of remaining changes you have in mind:
* do you plan to keep the numbers for the html files or rename these as well (`x1`, `x2` etc.)?
* should the `ch*-` part then get removed from the images as well or just for the ids/links? so will it stay `fig-ch2-main-pd-window.png` or become `fig-main-pd-window.png` then?

altogether, i agree that editing is less error prone that way. and another strong argument for all these changes is, that future links from anywhere (patches, help files, discussions on the internet) will remain stable that way. at the same time i wonder if we're possibly destroying too much with this step? can't really tell what "backlink" structure currently exists there.

currently, i see:
* [x] recreate data structure screenshots where necessary
* [ ] agree on naming scheme
* [x] consistent image names
* [x] remove numbers from ids and links

**Comment by Lucarda** [comment]
> do you plan to keep the numbers for the html files or rename these as well (x1, x2 etc.)?

the only reason i see for not changing it is that they are currently used in the internet. (if in doubt, lets keep it, i think)

> should the `ch*-` part then get removed from the images as well or just for the ids/links? so will it stay `fig-ch2-main-pd-window.png` or become `fig-main-pd-window.png` then?

yes. we can even go (optionally) without `fig`.

**Comment by Lucarda** [comment]
@porres and @ben-wes https://github.com/pure-data/pure-data/pull/2242 addresses "remove numbers from ids and links"

I wont be able to handle renaming on the pics but Ben has expressed already that he is ok with that and for Porres it gives the same so Ben if you find time and will just go ahead.

**Comment by ben-wes** [comment]
@Lucarda i didn't create a PR on this towards `pure-data/documentation` since maybe you might want to change or add stuff. but here's a commit that's based on your last changes including all changes for images that you can grab if it looks good to you:
https://github.com/Lucarda/pure-data/compare/html-slugs...ben-wes:pure-data:docs-img-rename?expand=1

**Comment by ben-wes** [comment]
ah ... and i once more forgot the makefile changes. adding these ...

**Comment by ben-wes** [comment]
@Lucarda: amended and force-pushed. should be ok now.

**Comment by porres** [comment]
Not sure what is going on here, and I was serious about the need to take a break

**Comment by Lucarda** [comment]
https://github.com/pure-data/pure-data/pull/2242

- includes commit from @ben-wes on renaming pics and extras

- putting back numbers in index and headings (as requested from @porres)

**Comment by porres** [comment]
for the record, I am not really following any of this or making any real and formal requests. I think I made myself pretty clear, on multiple occasions, that I am taking a break, that I need to take a break, that I am not looking at any of this right now. If I need to try and make myself clear once more, I am stressed, there's a lot going, and being ignored and dragged into this is only making me more stressed. Please, give me a break, forget about all this for the moment. I am not looking at any of this.

**Comment by Lucarda** [comment]
i'm not sure when you read this. yes you told us you had taken some time but we are still working. thats all. when you want to, you resume with the work. your time is yours.

**Comment by porres** [comment]
well, you're either wasting time working without discussing things with me, or you think I shouldn't discuss things (which you already made quite clear on a terrible authoritarian tone that drove me away and stressed me a lot).  I mentioned 3 times that I would take a break and I feel you ignored those requests or that you enjoyed this opportunity to push things the way you wanted and that you know I was against. 

A lot has happened yesterday and I could really use some time to get my mind straight, but I can't, I couldn't have a 24h break...to heal, to decompress, to come back better, and I am getting flooded with things that I wouldn't like to look or discuss right now. All of this is actually making me feel even worse than yesterday, when things got out of limits for me. 

I would kindly ask that you could just close this issue as it's escalating in a bad way, again... reboot it, whatever, ignore the PR, until we can sort a lot of things out as things got also personal and weren't sorted, before we even get to discuss bikeshedding again, of all things.

right now,

**Comment by porres** [comment]
I wrote this on the wrong issue, fuck...

**Comment by porres** [comment]
yeah, I'm closing this right now. Sorry, I was pushed and now a can of worms got opened

**Comment by Lucarda** [comment]
@porres why you have fallen in love with me in the first place? you shouldn't.

I know i'm a real artist and all that but here i just do normal computer work.

please behave.

**Comment by porres** [comment]
I really think this issue must be closed and archived as it’s gone sour and contaminated with sarcastic remarks on your behalf against me. I had closed it before that, so things wouldn’t escalate more… they escalated, and you reopened it.

Let’s try and have basic ground rules and not let things get inappropriate. This issue is not appropriate anymore and it must be rebooted. Please don’t take this as a personal attack and try to understand my reasoning. I think it is totally reasonable.

**Comment by umlaeute** [comment]
if things go OT,  you can hide (or even delete) individual posts. no need to start anew (which also takes a considerable amount of personal energy)

**Comment by porres** [comment]
you're right, but this is also kinda supposed to be the 4th reboot or so of what was more long chats and discussion of things, with over literally hundreds of messages, and not a proper and objective issue that we can just cirurgically edit to keep on track. So I thought and I could add that by "rebooting" this I'd hope that things could be objectively pointed out and discussed.

And as I mentioned in the lat discussed that I closed because escalated quite a bit (which is something ben also pointed when starting this new one), I would need to take a break from discussions to cool a bit, and also cause i'm really busy (and in the middle of a tour right now).

Things have kept escalating now and there's a PR that simply has no real connection to this issue anymore and is just @Lucarda trying to change things that had already been discussed long before and doing it I don't really know why, out of this context, just "because"? And with no discussion?

> well, you're either wasting time working without discussing things with me, or you think I shouldn't discuss things (which you already made quite clear on a terrible authoritarian tone that drove me away and stressed me a lot). I mentioned 3 times that I would take a break and I feel you ignored those requests or that you enjoyed this opportunity to push things the way you wanted and that you know I was against.

I'm perplexed this is still going on with yet new stuff... and now you just made a commit taking everything I did work on hours and hours and just messing completely with it and taking all that I added into an unrelated new chapter that has no reason to exist, at least you never pointed me one when we went over this and I said why a new chapter doesn't make sense.

The dynamics of this has gone really crazy. I thought I made myself clear last in https://github.com/pure-data/pddp/issues/190#issuecomment-2034982747

you either don't understand, or you're ignoring me intentionally... 

Please, don't waste more energy proposing things on commits that you know I don't agree, as we've been over it. At least, not without some sort of reasoning and discussion, but you're doing any of that and you went as far as saying you don't care about my opinion and that you don't want to discuss things. It's not gonna work like that...

So please, if anything, just open new issues that are objective, that don't mix a lot of stuff, which can then be properly discussed and coordinated before PRs can be made.

Now, did I mentioned I am really busy, on a tour and stuff? I guess I mentioned multiple times I could take a break. Can I have like a week please? I can then come back and focus on this.

Thanks

**Comment by porres** [comment]
as can be witnessed, I'm back at making manual revisions in my documentation branch, but focusing only and merely in text/content revision of chapter 2

I was triggered into working with the PR again because of someone who opened a doc related PR.

I hope this gets merged soon so I can take a break from working on that branch, when I'll create a new branch for manual revisions in my fork. Depending on time frame and release plans, I'll see if I can make more changes besides text revision of chapter 2 for the next release.

**Comment by porres** [comment]
hmmm, the recreated screenshots of data structures is something needed here in this context, actually. I'll see if I can find these or I guess i can also recreate them. I'll message you in private about this @ben-wes
