### ISSUE TITLE
use [poly] in the C10.monophonic.synth.pd example

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#229]
I noticed that we have a rather complicated mechanism to implement a monophonic synthesizer in C10.monophonic.synth.pd

On the other hand the J08.classicsynth.pd example simply throws in a [poly 1 1] object to handle the monophonic synth. And this was done without any explanation that [poly] can be used to manage simple polyphonic synths.

I just updated the [poly] help to also include a monophonic example and my idea is to also use [poly] and better explain how it can be used to manage simple polyphonic synths.

**Comment by porres** [comment]
here's the result 

<img width="535" alt="Screenshot 2024-07-06 at 20 10 35" src="https://github.com/pure-data/pddp/assets/5360142/692361ff-598d-4e94-87bb-941e3736c2d0">

**Comment by abreubacelar** [comment]
hmm, but what about Miller Puckette book? these examples should be in sync
with the book right? it would be awful to read the book and when you go to
check the example it is not the same....

so instead of changing the example, why not leaving a note for people to
check poly help file? and explain that the example was meant to use with
the book?

Em sáb., 6 de jul. de 2024 20:11, porres ***@***.***>
escreveu:

**Comment by abreubacelar** [comment]
for reference, this example is from here

https://msp.ucsd.edu/techniques/latest/book-html/node56.html

**Comment by porres** [comment]
I'm actually aware of the book, but my idea is to also update it, which seems like the natural and reasonable solution. By the way, other examples have been changed for a while already.
