### ISSUE TITLE
"Updated for" is not pertinent for the tutorials

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#231]
I see the need for the "Updated for Pd version x.xx-x" in the help file of objects, as it is a way to say when it last got an update.

I don't see a reason for any of that in the tutorials, control examples, audio examples, and data structures...

It is rare that these examples shall get updated anyway, and as I see it, the whole tutorial series should be mentioned as "being updated for Pd version x.xx-x"... it's kinda weird that some examples are updated for versions different than other examples...

If anything, the whole series should be synced to mention what Pd version it was last updated for... but also, it could simply be implied that whatever version you're running Pd that the version these tutorials were updated to are for that version itself.... that is to say, maybe simply just don't mention what Pd version it is for.

**Comment by porres** [comment]
> If anything, the whole series should be synced to mention what Pd version it was last updated for...

A way to do this, if that is the case, is simply defining this in the 1st example of the series, so whenever anything changes that is relevant, then just say the things was updated...

Like, even if just a single typo was fixed, it is worth noting that there was an update.

I say this because I've been making minor changes that are not significant, so I've kept the original "Updated for X.XX-X"... and I think that is wrong.

I did change the version when I updated an example to make use of a new Pd feature though, but it just occurred to me that is rather silly to look at one example that was supposed to be updated for some old Pd version, and another one that only runs on a more recent version.

what do you people say? Specially @millerpuckette of course

**Comment by umlaeute** [comment]
i think that once you've worked through the examples, you will only ever open specific ones.
so if you only define your "updated for" in the 1st example of a series, it will basically be lost to the user.

which begs the question: *who is the intended audience for this "last updated for" string?*
i think that there is little value for new users who work through the tutorials for the first time.
otoh, there might be merit when *re*visiting a given example (but as said above, re-visitors will likely miss the 1st example).

so this would be an argument for putting the information into each example.

personally I do not see much merit in these "updated for" strings for *examples* anyhow, so I could happily live without them altogether.

---
the other question is, *why should anbody want to know the "last updated" info?*
for reference patches, i think this information is useful to check if a given object has grown a new feature, or the API (data in, data out, args) has changed.
as such, bumping the version in the "last update" for typo fixes is not so much useful.
(in short: i think for help-patches, the "last updated" should refer to the last-update of the object itself, rather than the help-patch)

**Comment by millerpuckette** [comment]
There's only one rather weak reason to be putting that info int he 
examples, which is that a lot of people (me included) sometimes adapt 
them into our own projects (e.g., phase vocoder; PAF).  I think that if 
the update actually makes the result sound different from how it did 
before that would be worth putting in a note - the only example of that 
that I can think of would be the phase vocoder which I improved somewhat 
over the original version.

cheers

Miller

**Comment by porres** [comment]
> for reference patches, i think this information is useful to check if a given object has grown a new feature, or the API (data in, data out, args) has changed.
> as such, bumping the version in the "last update" for typo fixes is not so much useful.

I agree @umlaeute the idea to include whatever changes (typo fixes and stuff) was for the tutorial examples, not for reference help files, which I have only updated to refer to new functionalities indeed. 

> I think that if the update actually makes the result sound different from how it did before that would be worth putting in a note - the only example of that that I can think of would be the phase vocoder which I improved somewhat over the original version.

Yeah, well, in that regards, I bet this is a matter of exception rather than a rule, and the only exception here if from quite long ago, huh? I tried to dig it up. It seems it was last updated for 0.44!

Rather recently I did make significant cosmetic changes, but I think I kept the orignal last 'updated for 0.44' version for the phase vocoder. Nonetheless, I'm not sure why, and not knowing the actual criteria, I have recently changed to  'updated for 0.54', and obviously the changes were not significant at all, and I was only making more cosmetic changes. So... sorry :/ 

For some other examples I did update the version to refer to new functionalities like using [clone], but it was kind of arbitrary, becasuse [clone] was introduced in 0.46 if I'm not mistaken and I used some other more recent version at the time (52?).

Well, anyway, if we agree that this information is not really useful for tutorial examples, I guess we can just get rid of it. Now, for exception cases, we can include a note, and say in the phase vocoder examples (for instance) that the patch changed the quality of the sound produced by the patch in version 0.44 if compared to the previous versions.
