### ISSUE TITLE
Update Pd-l2ork and Purr Data entries in 'downloads' on puredata.info

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#33]
The https://puredata.info/downloads/Pd-L2Ork page linked in feature downloads is a bit of a mess and outdated. I can't edit these (I guess only the authors can). I remember once asking them to change something but now it's just worse. 

I explained the current situation nicely and well summarized in the front page and I also added working links to their websites, so I think this is cool and does it.

I also added Pd-Ceammc along Pd-l2ork/Purr Data

ping @umlaeute , can we remove it from 'featured downloads'? their pages can still be there and sit around, even though they are outdated. Authors are invited to update their page and we can put it back if it ever happens.

**Comment by porres** [comment]
we can also invite the authors of Pd-Ceammc to create a page of their own so we can add it to the featured downloads. I actually already asked them to do it a while back, and they never did... but I can ask again.

**Comment by porres** [comment]
> we can also invite the authors of Pd-Ceammc to create a page of their own so we can add it to the featured downloads. I actually already asked them to do it a while back, and they never did... but I can ask again.

Hey, they actually made a page already, so it can go into featured downloads too ;) see
http://puredata.info/downloads/ceammc

**Comment by porres** [comment]
Let me just emphsize that the download page of Pd-l2ork talks about releases from 2015 and of a pd-l2ork 1.x just for linux (when now it also has a cross platform 2.x version). So it's all just noise, misleading information and pure confusion. My text on the front page pretty much solves and sorts everything for good and for the foreseeable future.

**Comment by umlaeute** [comment]
1. what is this topic exactly about?
   - removing purr-data from the featured downloads (as the title suggests)
   - removing pd-l2ork from the featured downloads (as the description suggests)
   - updating the pd-l2ork download page (http://l2ork.music.vt.edu/main/make-your-own-l2ork/software/) to include the latest release
   - adding pd-ceammc to the featured downloads

all of them are related (get the latest version of Pd forks without being confused by outdated versions), but require quite different actions.
of course it does not help that the situation for at least pd-l2ork/purr-data is confusing (the confusion is best expressed by the name "pd-l2ork/purr-data" where it is simply unclear what the name of the project should actually be).


my personal preference of action would be:

###  fix the front page

> My text on the front page pretty much solves and sorts everything for good and for the foreseeable future.

the web page lacks history browsing so i cannot really compare your new version with one from last week. but the section about forks still looks confusing to me.

it may be a simple layout issue though.

esp. sentences like "Pd Vanilla, which may also be just considered another distribution of Pd" just doesn't add any useful information


### replace "pd-l2ork" with "purr-data" and link to "https://purrdata.net" instead.

afaict, pd-l2ork is dead by now and has been replaced by purr data (as in: purr data includes the entirety of pd-l2ork, pd-l2ork is no longer developed as such and seems pretty abandoned anyhow, at least it's [obvious homepage](http://l2ork.music.vt.edu/main/make-your-own-l2ork/software/) lists outdated software).

otoh, there is a git-repository https://github.com/pd-l2ork/pd-l2ork which has seen it's last push 2 days ago...

i think only @pd-l2ork, @agraef or @jonwwilkes can answer what ought to be done here.

(if it is all the same to them, we might as well completely remove it; OR it could be that the pd-l2ork page *we* consider outdated is still the reference download page and there is just no reason the change it).

### add pd-ceammc to the featured downloads

maybe, i really don't know. what would make it qualified for a "featured download"?
there's a number of "forks" out there, what makes pd-ceammc special?

we already have a "distributions" category, that lists all the forks (it *probably* should be changed to only list each project once, rather than each release of each project).

otoh, i do not want to dismiss the idea of featuring them.

**Comment by porres** [comment]
> afaict, pd-l2ork is dead by now and has been replaced by purr data

nope. I know, it's confusing! If I get it correctly, here's the deal.

In 2009, Ivica Buckvic started developing Pd-L2Ork, only available for Linux. Released from march 2017, “Purr Data” is Jonathan Wilkes' cross-platform Pd-L2Ork version. Purr Data also uses the Pd-L2Ork name (but at version 2.x), which can be confusing. Purr Data (Pd-L2Ork 2.x) ported Pd-L2Ork to nw.js and Pd-l2ork 1.x was still kept around.
	As of august 2021, Pd-L2Ork started offering new releases based on the same version number as Purr Data. This is extremely confusing and requires Purr Data to stop using the “Pd-L2Ork” name to avoid throwing people off (hopefully this will happen soon). The new Pd-L2Ork 2.x versions now builds on Purr-Data's nw.js front-end, so it’s about the same thing. The difference is that it focuses on bringing back features from the Pd-L2Ork 1.x that didn’t make into Purr Data, plus a number of new features designed to improve usability and stability. 

So yeah, quite confusing and I did my best in the front page to explain this in just a few words. I also gave links to both purr data (jonathan's) and pd-l2ork (ivica's site).

The download pages on the site are outdated and don't present any of this information. I wouldn't like to remove it from 'featured downloads' but the information there needs to be updated and I can't do that (I don't have editing powers). So they have to do it (they're the ones who can only do it, right?) and we put it back when it's updated.

**Comment by porres** [comment]
> maybe, i really don't know. what would make it qualified for a "featured download"?
> there's a number of "forks" out there, what makes pd-ceammc special?

There are not that many 'forks' out there, 'purr/l2ork' and 'ceammc' are the only two I consider worth noting(1). What makes it less special than 'purr/l2ork' to not be featured? And they do have an updated page in puredata with a release from a few days ago, what other fork has that (that we'd be not giving the same importance)? 

(1) 'pd-next' might be another? but that has quite minor changes and no page in puredata.info.

**Comment by porres** [comment]
> sentences like "Pd Vanilla, which may also be just considered another distribution of Pd" just doesn't add any useful information

removed it

**Comment by porres** [comment]
well, issue now is just about purr/l2ork - ceammc has a new dedicated one.

**Comment by Ant1r** [comment]
> link to "https://purrdata.net"

this link doesn't seem to respond... but https://www.purrdata.net does.

**Comment by porres** [comment]
I just used https://agraef.github.io/purr-data/ though

> abandoned anyhow, at least it's obvious homepage lists outdated software).

just to be clear, this page carries updated 2.x software
<img width="599" alt="Screen Shot 2021-11-23 at 07 42 43" src="https://user-images.githubusercontent.com/5360142/143010238-cffa44ac-441d-47bb-9621-bf1af2c32cf2.png">

**Comment by danomatika** [comment]
Are the individual project/fork info pages in the plone CM/S editable by the respective project owners? It makes sense to me to allow them to keep their own info pages up to date and just list them from the main list.

I know no one seems to want to use plone anymore but it is just a wiki system, more or less…

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by umlaeute** [comment]
@danomatika asked:
> Are the individual project/fork info pages in the plone CM/S editable by the respective project owners?

they are of course editable by the plone content owners.

- ico is the owner of the Pd-L2Ork project (in the context of the webpage), so he can update whatever info he wants to.
- there is no separate project for Purr-Data

@porres wrote:
> just to be clear, this page carries updated 2.x software (hence I linked to it as well)

so what is the problem then?
the "featured download" link brings users to an intermediate project webpage (on puredata.info).
when people click on "download" they get to the official pd-l2ork webpage were they get the latest and greatest version.

> I just used https://agraef.github.io/purr-data/ though

while @agraef does a great job packaging purr-data, this doesn't exactly *look* like the official project webpage.
i'd rather not track who is responsible for what in the purr data universe and would like to direct people to a single place.
https://www.purrdata.net (thanks @Ant1r for noticing the `www.` prefix) looks like a good candidate, but it probably isn't as the linux download links point to a page that requires login (and albert's page isn't there at all).

> So yeah, quite confusing and I did my best in the front page to explain this in just a few words.

i think it is too many words.
the welcome page mostly talks about forks and flavours. this is not the first thing i want to know about a software.

**Comment by porres** [comment]
> so what is the problem then?
> the "featured download" link brings users to an intermediate 
> project webpage (on puredata.info).

what do you mean by 'intermediate'?

The link brings us to https://puredata.info/downloads/Pd-L2Ork , it mentions pd-l2ork is at version 1.0 and for linux only. A mac user won't know there's a 2.0 version for mac on the link and won't click. You thought that the link was outdated to an old abandoned/unmantained  1.x version yourself! They also mention the latest release as being from 2015, well, I just think this should be updated to reflect the current state.

> i think it is too many words.
> the welcome page mostly talks about forks and flavours. this is not the first thing i want to know about a software.

yeah, best thing would be to direct to the pages for more details, but the way it s right now isn't much more text than before.

**Comment by porres** [comment]
> i think it is too many words.

made it even shorter now, this is basically as much text as before on purr, so I just added a short paragraph on ceammc as extra stuff.

**Comment by umlaeute** [comment]
Am 23. November 2021 16:34:00 MEZ schrieb porres ***@***.***>:
>> so what is the problem then?
>> the "featured download" link brings users to an intermediate 
>> project webpage (on puredata.info).
>
>what do you mean by 'intermediate'?
>
>The link brings us to https://puredata.info/downloads/Pd-L2Ork , it mentions pd-l2ork is at version 1.0

Afaics it mentions both version 1.x and 2.x

> and for linux only. A mac user won't know there's a 2.0
> version for mac on the link and won't click. 


the page also says:
> Purr-Data, supports all platforms

I agree that the download icon should be made platform independent (no more tux :-/)


> They also mention the latest release as being from 2015, well, I just think this should be updated to reflect the current state.

the puredata.info project page says that:
> Please note pd-l2ork continues to be developed on a regular basis with over dozen minor releases since the last major release posted on puredata.info


> You thought that the link was outdated to an old abandoned/unmantained  1.x version yourself!


Hmm, did I?

I think I just responded to your mail without checking the actual puredata.info project page.

afaict, "my" facts are:
- I know that the project page is not updated (regularly)
- I was aware that this is not ideal, however
- I was "pretty sure" that the actual 'download' link just redirects to some "official" page that has the current version
- you come and say everything is outdated
- I do a casual check of the official PD-l2ork page and it *does* look outdated (it only mentions 2015)
- you say that the problem is not the official page, but the project page on puredata.info
- I check the project page and it doesn't seem to have significantly diverging info from the official page 

so to conclude: I don't see much fault in the featured downloads mentioning PD-l2ork, nor in the project page, on puredata.info
If you think that the official PD-l2ork page should be updated, then that's fine for me but it is not something *I* want to discuss (having no core interest in l2ork/purr).

In general I think it is the responsibility of the "project owners" on puredata.info to update their project descriptions/releases

**Comment by porres** [comment]
> Afaics it mentions both version 1.x and 2.x

not really, again, it's confusing, and that's been my point! But when it reffers to 2.x it's reffering to Purr Data, not Pd-l2ork 2.x... which again proves my point on how misleading this is :) not to mention outdated. Again, they should update to mention how Pd-l2ork is now at version 2.x and that it differs from Purr Data but it's also cross platform.

> you say that the problem is not the official page, but the project page on puredata.info

yup!

> In general I think it is the responsibility of the "project owners" on puredata.info to update their project descriptions/releases

yeah, I know. Well, we can just ask them to update this then... but you know, I already gave this information on the front page and don't care anymore than this. They've been flagged here and hopefully they can see and update it.

**Comment by pd-l2ork** [comment]
Pd-L2Ork is now an independent project from Purr-Data. It has had over
dozen releases in the last two months alone. I originally created that
content but haven't bothered updating it be sure the interface is difficult
to navigate. Happy to take a stab at updating it. Purr-Data should be given
a separate entry. Hope this helps.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by porres** [comment]
It would in fact make more sense and help sorting things out to give them separate entries!

**Comment by porres** [comment]
Well, in fact, there is a separate entry for Purr Data, see https://puredata.info/downloads/purr-data

**Comment by porres** [comment]
I've renamed and am reopening this. I also consider that the current situation  is quite recent and the projects are on their time to reorganize and better present the distinction. But I consider very important to update this in puredata.info as soon as possible.

**Comment by porres** [comment]
> I've renamed

maybe I should have, I guess it makes sense to close this and start over, but I still think it makes no sense to keep 'Pd-l2ork' in a 'featured download' when the entry is so outdated!

**Comment by porres** [comment]
rebooting this at https://github.com/pure-data/pddp/issues/38

**Comment by umlaeute** [comment]
i still don't see what there actually is to update.

- as noted in #38, i've added a new *generic* release for the "Pd-l2ork" project
- i've added a generic download link to the "Purr Data" project

**Comment by porres** [comment]
> i still don't see what there actually is to update.

I respond to this in https://github.com/pure-data/pddp/issues/38
