### ISSUE TITLE
puredata.info: Update 'Pd-L2ork' entry in 'featured downloads' or remove it from it.

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#38]
I'm not sure what qualifies for a 'featured download' in puredata.info, but it seems natural to me it'd refer to some hot new release, that can be one of different categories under 'downloads' (a 'library', a 'distribution', etc.).

Well, 'pd-l2ork' is now featured but the entry is very old, much of this has been discussed in https://github.com/pure-data/pddp/issues/33 In fact, both _pd-l2ork_ ( https://puredata.info/downloads/Pd-L2Ork )  and _purr data_ ( https://puredata.info/downloads/purr-data ) entries must be update to reflect their current state. 

As far as what 'featured downloads' should reflect, it can't be such an outdated entry.  For instance, as a featured download, https://puredata.info/downloads/pure-data is always up to date.

By the way, I remember I suggested we updated that feature download section bacck in 2015 to finally remove 'Pd-extended' from it. It didn't make sense then to keep promoting extended as a featured download... well, 6 years have passed, maybe it's time to update this again.

It seems @pd-l2ork have already worked on a new entry, please go for it as the author is the only one who can update the entry (which should happen regardless of what's in a 'featured dowload').

**Comment by umlaeute** [comment]
i still do not see what you would like to change to make it less "outdated".

in any case i added a new dummy release for "pd-l2ork" that just says "latest" (no version number or year) and drops the release notes (so it doesn't announce old additions).

the download button now says "all platforms" (and no longer shows a linux logo).

i think that should resolve all issues. (we might rename the download back to "Pd-L2ork" only, rather than saying "Pd-L2ork and Purr Data" because i think this is just confusing everybody.

**Comment by umlaeute** [comment]
we *probably* could replace the "Pd-l2ork" feature with a "Purr Data" feature (as this is what has got the most traction)

**Comment by porres** [comment]
> i still do not see what you would like to change to make it less "outdated".

Ok, well, specially, this section is outdated and misleading:

- **Pd-L2Ork 1.0 was originally developed for Virginia Tech's Linux Laptop Orchestra (L2Ork). The new version 2.0, a.k.a. Purr-Data is developed by Jonathan Wilkes.**

It gives the idea that:
- Pd-l2ork stopped at version 1.x
- Purr Data is the same thing as Pd-l2ork, but at version 2.x (hence, the current download)
- When you point the link to the latest people are expecting "Purr Data", but that's not where you're heading (it's Pd-l2ork instead).

Suggestion, rephrase to 
- **Pd-L2Ork was originally developed for Virginia Tech's Linux Laptop Orchestra (L2Ork). The new version 2.0 uses the port made by jonathan wilkens' Purr-Data to nw.js and is cross platform.**

**Comment by porres** [comment]
In "project description" we also need to rephrase and sort things out! But I'll leave that to @pd-l2ork

**Comment by umlaeute** [comment]
> It gives the idea that:

but this is how upstream describes the project themselves!

quoting [purr data](https://git.purrdata.net/jwilkes/purr-data#relationship-of-purr-data-to-pure-data):

> - Purr Data. This is the 2.0 version of Pd-l2ork. It ships with lots of external libraries and uses a modern GUI written using HTML5.
> - Pd-L2Ork 1.0, the version used by Ivica Bukvic for his laptop orchestra. Pd-l2ork 1.0 uses tcl/tk (and tkpath) for the GUI.

and albert's [github page](https://agraef.github.io/purr-data/#the-name) says:
> Purr Data is the official nickname of the Pd-l2ork 2.x branch.

i haven't found a single page in the purr-data/pd-l2ork universe that clarifies the relation between the two beyond "Purr Data is the Pd-L2Ork 2.x".

so why should puredata.info impose such information onto the user?
it's a mess. i don't think *we* can do anything about it. (or put otherwise: what is the criterion for closing this issue?)

**Comment by umlaeute** [comment]
> what is the criterion for closing this issue?

now that i've removed pd-l2ork from the "featured downloads", should we close this?

**Comment by porres** [comment]
> what is the criterion for closing this issue?

The idea is to have pages on the feature downloads that are up to date.  So either a) Update the entries; or B) Remove them.

> i haven't found anything in the purr-data/pd-l2ork universe (though my websearch foo may be lacking) that clarifies the relation between the two beyond "Purr Data is the Pd-L2Ork 2.x". 

I know, and I understand this is recent and it's still reasonable to not have better announcements.

> If you have some "official" resources that do so, please share them.

I don't, they don't, no one has apparently.

> why should puredata.info impose such information onto the user?

I don't know about "imposition", it's just an accurate and correct information, and being a portal about Pd, it's nice that it offers up to date and correct information.

> but this is how upstream describes the project themselves!

I know, and that's wrong/outdated information, what can I do?

> now that i've removed pd-l2ork from the "featured downloads", should we close this?

now 'purr data' is featured and we still have noise/confusion, as it says "Unlike "classic" Pd-l2ork, it is cross-platform and runs on Linux, macOS and Windows." - but Pd-l2ork is now cross platform as well.

Pd-ceammc seems like a better candidate to be featured at the moment.

**Comment by umlaeute** [comment]
> > why should puredata.info impose such information onto the user?
> 
> I don't know about "imposition", it's just an accurate and correct information, and being a portal about Pd, it's nice that it offers up to date and correct information.

fair enough.

> 
> > but this is how upstream describes the project themselves!
> 
> I know, and that's wrong/outdated information, what can I do?

probably nothing.

but the outdatedness (as it is) is probably less harmful than you might think.

> 
> > now that i've removed pd-l2ork from the "featured downloads", should we close this?
> 
> now 'purr data' is featured and we still have noise/confusion, as it says "Unlike "classic" Pd-l2ork, it is cross-platform and runs on Linux, macOS and Windows." - but Pd-l2ork is now cross platform as well.

but not "classic" Pd-l2ork.

> Pd-ceammc seems like a better candidate to be featured at the moment.

but only because the information available is less ambiguous.

i think the "featured downloads" should feature projects that people want to try out.
in my experience, people either want Pd-vanilla or the "new fancy thing" (which is Purr Data; rather than Pd-L2Ork)

**Comment by abreubacelar** [comment]
> i think the "featured downloads" should feature projects that people want to try out. in my experience, people either want Pd-vanilla or the "new fancy thing" (which is Purr Data; rather than Pd-L2Ork)

hmm, i don't know if this is the right place to this suggestion, maybe i could open another issue or open the discussion directly on pd list where more people could join, but, In the last year (or years, i don't remember) i have seen something different about this. 

in my perspective, different communities have gone in different directions (so consider this as my opinion only, nothing proved):

on facebook group i see people favouring pd-vanilla with deken, at the same time that people that still uses pd-extended lives (yeah, these people exists, and also i saw people that still teaches with pd-extended...),  together with people that hates purrdata and people that uses purrdata but don't ask many questions (probably because people will arrive and ask why they are using purrdata? i see this as negative react..., but not everyone is like these people), but there is also interest in pd-ceammc, as uliss post new releases there and people react positively, and people also ask or discover about pd-next when asking about colors in pd, or changing themes (rather than being suggested to purrdata, that also have some of these features iirc).

In Discord group, i see many people favouring pd-next together with pd-vanilla (yeah, people share and help each other with their themes, and how to start changing colors), i saw people asking about pd-ceammc, but not many people are using it there i think, and people respect who uses purrdata, but often they share bad experiences about crashes, but nothing really against its use (sometimes they even suggest that you install both, so if you need to open a patch from someone else that was created on purrdata you don't have trouble with its incompatibilities with pd-vanilla).

(i don't go often to other communities... shame on me, but would be interesting to know what the trend is on reddit, and i suppose pd forum is all about pd vanilla, but i should go there and read for myself...)

but as i said this isn't evidence of anything. Based on what i see, i would feature, together with vanilla, these 3 flavors (pd-next, purrdata and pd-ceammc) that i am seeing people want to try and are asking about... but what about if we change the perspective and actually ask the communities what they think about what should be featured? Maybe puredata.info could have some poll mechanism where the users could vote for additional featured downloads, so maybe highlighting externals, or projects, together with the distributions? Maybe this would benefit also people to go more often at puredata.info and feel it more about a place to get news about puredata "universe", what is new and what is being talked about.

**Comment by porres** [comment]
@abreubacelar, I created a discussion for this => https://github.com/pure-data/pddp/discussions/42 please remove this comment from this issue thread and post your considerations there. You can email people on the Pd-list (or elsewhere) to join the discussion there. 

But note that I don't think the discussion is about what people think of projects, that's a rather subjective criteria.

And as someone who always asks why some people are not using Vanilla, that's a very important question to ask because I've seen an incredible amount of people that have the wrong idea and assumption that Pd-Vanilla was abandoned. Or that now that Pd-Extended is abandoned they have to use Purr Data as the only possible choice. So my concern is to get things straight, point some of the facts that mostly seem oblivious to people.

Anyway, let's move this there!

**Comment by porres** [comment]
> probably nothing.

well, I think I have put some nice and accurate information on the front page, that's nice.

> but the outdatedness (as it is) is probably less harmful than you might think.

it's not that much of a big deal, I already said it's also still a reasonable flaw. And it's easy for them just to update it (hopefully soon) and that'll sort things out.

**Comment by porres** [comment]
anyway, closing this again in favour of the new discussion in https://github.com/pure-data/pddp/discussions/42 where we seem to have more to talk about.

as far as updated entries for purr data and pd-l2ork, we just need to ask them to do it and I guess they have it on their to do list (they have to first sort it out in their main project description before fixing things elsewhere).

**Comment by pd-l2ork** [comment]
If you try the new Pd-L2Ork 2.x you may realize it is Purr-Data plus tons
of improvements. So, before disseminating (mis)information, it may be
helpful to test things first.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by pd-l2ork** [comment]
Why would you do this without consulting the original author or reading my
replies?

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by porres** [comment]
> Why would you do this without consulting the original author or reading my
> replies?

I don't know who you are responding to. I'm aware of your state of the project, I haven't done anything, and no one here is disseminating misinformation, the only official information provided in puredata.info is from the authors of the pages, you (for pd-l2ork) and agraef (for Purr Data). If anything is wrong or misinformed in the entry on purr data, it has nothing to do with anybody other than the author.

It seems you assumed that someone edited your entry on puredata info or deleted it. I explained that didn't happen in https://github.com/pure-data/pddp/issues/43

All that happened is that @umlaeute removed pd-l2ork from the featured downloads, see https://github.com/pure-data/pddp/issues/38#issuecomment-977781827

It seems purr data got in instead. This doesn't mean your page was deleted from puredata.info or edited.

What goes on in featured downloads is something we can debate and is not the decision of any author of any downloadable project. This issue refers to a discussion that is opened about it.

**Comment by pd-l2ork** [comment]
Somewhere in this web of open issues someone mentioned that pd-l2ork page was out of date. While I am should edit some of the wording to more accurately reflect the current state, the releases accessible via the links are current, with the latest 2.x release being on Nov. 13th. Given how convoluted the release system is on the puredata.info, and how much of that is redundant considering the access to the same information is already available via the external link, my preference is not to double the amount of work and keep it as a universal external link to the project page.

**Comment by pd-l2ork** [comment]
Thanks for your reply. Then, before we edit the featured list why don't we
first debate it? This would at the very least require reverting the list
before moving forward. Pd-L2Ork based on its age is as far as I can tell
one of the longest maintained pd variant, of which Purr-Data is, by
definition a sub-variant.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by porres** [comment]
yeah, my idea was to first generate a debate and then decide... but it's also not that much of a big deal, we're all acting here on good faith and improving things one way or another.

Now, this issue was updating Pd-L2Ork's page on puredta.info here. I see your changes and I have a revision. You say "launched in the fall 2020", but that's 2021, right? I know with the pandemic we're all confused with the concept of time :)

**Comment by pd-l2ork** [comment]
No, 2020 is correct. Pd-L2Ork has been developed independently since the
fall 2020.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net
