### ISSUE TITLE
Pd-L2Ork was removed/renamed without consulting authors

### ISSUE THREAD

**Issue by pd-l2ork** [pure-data/pddp#43]
Issue #33 has apparently edited my own work and rephrased it into Purr-Data without any consultation with it's original author (me). Please revert the featured link as it was because there are 2 variants, Pd-L2Ork and Purr-Data and they are not the same. Pd-L2Ork 2.x which seeks to combine and expand both Pd-L2Ork 1.x and Purr-Data has had over dozen releases in the past 2 months. At the very least you can have both Pd-L2Ork and Purr-Data as featured variants. Lastly, please do not edit work of others without consulting them first.

**Comment by porres** [comment]
Hi, I'm not sure if it is possible to edit your work, not being the author. I'm understanding you believe your page was edited to become 'purr data' instead, but that's not what happened. Your pages is still here, unedited: https://puredata.info/downloads/Pd-L2Ork

What seems to have happened is that the link was removed from the featured downloads and, apparently, the purr data entry took it place, either automatically or on purpose. Purr Data's page is authored by agraef, see => https://puredata.info/downloads/purr-data

If I understand, the decision to choose what the featured download is depends on the site's administrator (not me or you).

As far as what we believe should be featured, there is a discussion I opened here for that => https://github.com/pure-data/pddp/discussions/42 and we can have further discussions there. For now I am considering this issue invalid, but you can reopen if you will. 

> At the very least you can have both Pd-L2Ork and
> Purr-Data as featured variants.

I guess so, and also more, or maybe one entry that correctly talks about both, I dunno, we can discuss it in https://github.com/pure-data/pddp/discussions/42

But my only remark is that a featured download should have an up to date information. It seems neither yours or purr data's entry do reflect the current state of the projects, neither the oficial websites outside of puredata.info. I kindly ask you consider working on this so everyone is better aware of the current state of these projects.

**Comment by porres** [comment]
by the way, as far as highlighting both of your projects, there's a new update for the front page of puredata.info for a couple of days now that points to downloads of both projects and correctly states the current state of affairs.

**Comment by umlaeute** [comment]
@porres please do not close this issue until we found a reasonable solution that makes everybody happy (as can be).

> Hi, I'm not sure if it is possible to edit your work

not for mere mortals. but i (as admin of puredata.info) can do that and i did.
so it's *mea culpa*.

so i'd like to resolve this issue.

first i want to state that what i did was done in *good faith* - i never intended to do any change to the content that somebody would object to.

in any case, i would like to go forward rather than revert the old state (and thus go backward), but of course i would also like to get a satisfying solution for everybody involved.

## what did i change?
this is of course the most interesting question, and i'll try to remember what i did (with the help of archive.org).

###  the "featured downloads" on the main page

i replaced the feature of "Pd-L2Ork" with a feature of "Purr Data"

### the "featured downloads" on the [downloads](https://puredata.info/downloads) page

i replaced the feature of "Pd-L2Ork" with a feature of "Purr Data"

### the category sections on the [downloads](https://puredata.info/downloads) page

i changed the display so that each category would display the 5 projects that had the most recent releases ("releases" within the puredata.info portal).
previously it listed the five most recent releases (if a single project would have 5 release in the last 5 days, it would kick out all the other projects; now only the latest release of a project is shown)

### the "Pd-L2Ork" project page

0. i changed the name from "*Pd-L2Ork and Purr-Data*" to "*Pd-L2Ork*"
1. i did not change anything on the main project description
2. i did create a new "release" with the following features:
    - version is `current`
    - a download button shows a green arrow and says
      > Get Pd-L2Ork for All platforms [packages for all supported platforms]
    - the "release summary" says:
      > get the latest and greatest Pd-L2ork/Purr Data from the project's homepage"

plone automatically shows parts of the latest release on the project page (that's why the page now effectively looks different).

for reference the previous release (that was shown beforehand) had the following features:
- version is `20151223`
- a download button shows the image of tux and says
  > Get Pd-L2Ork and Purr-Data for Linux (28MB) [Ubuntu 15.10 64-bit deb (also available as a source tarball)]
- the "release summary" says:
  > Linux Laptop Orchestra's pd-l2ork offers a slew of usability improvements and a large collection of 3rd party externals. This is likely the last major release before transitioning from tkpath onto node-webkit renderer. Please note pd-l2ork continues to be developed on a regular basis with over dozen minor releases since the last major release posted on puredata.info. Once again, tons of new updates, most notably expanded K12 module including Raspberry PI GPIO with comprehensive PWM and I2S support, bunch of small improvements and bug fixes (e.g. comments with endlines or iemgui labels with spaces), documentation improvements, and comprehensive Wiimote support using a custom libcwiid fork (included in the source, also available as a separately downloadable tarball) offering interleaved motion plus and expansion data retrieval, as well as recently added support for the new version of MotionPlus Inside wiimotes. Pd-L2Ork is a monolithic release that includes most of the pd-extended libraries in one convenient package with a growing number of externals having their own standardized help files. In this latest version, pd-l2ork can be installed alongside other pd variants and there are no lingering conflicts between various packages.


### the "Purr Data" project page
1. i did not touch the project description itself
2. i *did* change the current release (2.x) slightly, namely:
    - i changed the release summary to read:
      > All Purr Data releases can be found on its Github mirror
    - i added a download button that shows a green arrow and says
       > Get Purr Data for All platforms [packages for all supported platforms]

       the button links to https://github.com/agraef/purr-data/releases .


for reference, previously it showed the following:
- the  "release summary" said:
  > All Purr Data releases can be found on its Github mirror at https‎://github.com/agraef/purr-data/releases.

  (not that the URL was not clickable)

- no download button existed

**Comment by umlaeute** [comment]
so now that i have described *what* i did, i would also like to say *why* i did it:

### replacing "Pd-L2Ork" with "Purr Data" in the *featured downloads*

i see the "Featured Downloads" as a way to help people navigate the page, by giving them what they are looking for without too much noise
- the features should represent what most people actually do want to download
- the "feature" should stand out visually, so people find it quickly
- the set of featured articles ought to be small (2 seems to be a good value; after that it becomes just another "list")

in my personal experience, people tend to ask for "Purr Data" rather than "Pd-L2Ork".
this is the (only) reason why i decided (as editor of the page) to replace "Pd-L2Ork" with "Purr Data".

your perception what people ask for, will obviously depend on your POV.

### changing the release description for "Purr Data 2.x"

honestly i think this was just cosmetics: i've replace a non-clickable link with a working download button.

does anybody object to this?


### changes to "Pd-L2Ork"

this is obviously the most problematic of my edits, as i was trespassing onto ico's content

#### renaming "Pd-L2Ork and Purr-Data" to "Pd-L2Ork"

given that there is a separate "Purr Data" project, i think it is just confusing to have another one with the same name.


### adding a new release to "Pd-L2Ork"

as said, my changes were meant as improvements rather than vandalism:
- the version "number" now says `current` rather than `20151223` in order to indicate that the project is still alive and kicking (and hasn't ceased 6 years ago)
- the download button image is now obviously for all platforms and not only for Linux (so macOS and Windows people also have a place to click)
- the download button description no longer says "Ubuntu 15.10", as this (again) does not address macOS and Windows people and probably doesn't address Linux people either
- the release description was shortened to a generic (but hopefully positive) sentence.
  the original description was obviously outdated with things like "This is likely the last major release before transitioning from tkpath onto node-webkit renderer."
  my idea was, that it is better to have a generic description in places that don't change so often (the puredata.info project page) and get people faster to the "real" project page (at Virginia Tech) were the information would be kept up-to-date.

**Comment by umlaeute** [comment]
> Lastly, please do not edit work of others without consulting them first.

so now that i have hopefully made clear why i did what, @pd-l2ork which of your content do you (still) want to be reverted?

**Comment by pd-l2ork** [comment]
So, I just updated the Pd-L2Ork entries and made sure that there is a
generic link consistently pointing to the latest releases available on the
L2Ork's website. Regarding reverting of the content, I would like to have
pd-l2ork reinstated as one of the featured links with the L2Ork logo.
Thanks.

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Director, Human-Centered Design iPhD
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by umlaeute** [comment]
thanks for updating the Pd-L2Ork entries.

whether "Pd-L2Ork" or some other software is going to be on the "featured downloads" is another issue and can be debated on #42 

so if nobody objects, i'm closing this ticket for now.

**Comment by pd-l2ork** [comment]
Closing the ticket is ok with me. However, before we edit the featured
list, if there is a planned debate on this topic, then we need to first
debate it. This would at the very least require reverting the list to its
prior state before moving forward. Pd-L2Ork, based on its age, is as far as
I can tell one of the longest maintained pd variant, of which Purr-Data is,
by definition a sub-variant.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by porres** [comment]
@umlaeute, I see you made other changes to the main page as well.

I'm editing it too,  changed

"Other Pd flavours" to "Main Pd flavours", because you have Pd-Vanilla in that list.

I edited The mentionings for Pd-l2ork/Purr data as I don't agree with the changes. Also, taking into consideration the updates by @pd-l2ork in its entry, I don't think Ivica approves your mentioning that Pd-L2Ork is "based on Purr Data" (ivica, please check the frontpage of puredata.info and share your thoughts).

For instance, you made the remark that exterals for Purr Data are not guaranteed to run in Pd-Vanilla. That is vague and doesn't reflect what usually happens. I don't actually know of new libraries being developed just for Purr Data/Pd-L2Ork that includes HTML5 code that don't run in Pd flavours based on tcl/tk. It's more the other way around, so I put that information back, but rephrased.

Also, my original point is that there are some incompatibilities between Pd-Vanilla and these forks. They both have numerous changes, native core objects, different syntax ($0 in messages / $@ in arguments), different behaviour of some native objects (trigger has constant values as arguments). The latest versions don't necessarily include the latest additions to Pd-Vanilla and I can go on and on with the details, but the point is that incompatibilities are not only in respect to externals compatibility and the way I had phrased things before implied that the compatibility issues did not restrict to externals.

Please let's discuss what can be the problems with the information I am presenting on the front page to see what is the best way of putting things.

Since the page can be edited and changes lost, here's a snapshot of how I left this.

<img width="886" alt="Screen Shot 2021-11-25 at 16 16 01" src="https://user-images.githubusercontent.com/5360142/143492093-d7cf0a45-3c7b-44fe-aef4-75f864a7fed7.png">

**Comment by porres** [comment]
ok, here's a new snapshot of how I left (since it can be edited and lost).

<img width="883" alt="Screen Shot 2021-11-25 at 16 18 57" src="https://user-images.githubusercontent.com/5360142/143492311-a00286ab-14bc-45cf-84e1-a9777ac7db18.png">

**Comment by pd-l2ork** [comment]
Thanks. I will review this soon. One thing that should be adjusted
immediately is alphabetical order of project names to avoid suggesting any
kind of hierarchy. Vanilla should be listed first, and then everything else
alphabetically ordered. This may mean that some of the incompatibilities
should be mentioned inside Pd-L2Ork description, since it will be listed
before Purr-Data. This will also make more sense since Purr-Data is
effectively a Pd-L2Ork variant that for a limited time served as the home
for both Purr-Data and Pd-L2Ork.

Best,

Ico

-- 
Ivica Ico Bukvic, D.M.A.
Director, Creativity + Innovation
Institute for Creativity, Arts, and Technology

Virginia Tech
Creative Technologies in Music
School of Performing Arts – 0141
Blacksburg, VA 24061
(540) 231-6139
***@***.***

ci.icat.vt.edu
l2ork.icat.vt.edu
ico.bukvic.net

**Comment by porres** [comment]
yeah, I think I can make it work in any way

**Comment by porres** [comment]
> yeah, I think I can make it work in any way

Done

<img width="985" alt="Screen Shot 2021-11-28 at 12 01 21" src="https://user-images.githubusercontent.com/5360142/143773473-31a52ef1-5bcf-4474-91c2-65e466638083.png">

**Comment by pd-l2ork** [comment]
It appears the featured page still has only of and Purr-Data and has not been reverted to the previous state. See http://puredata.info/downloads/featured
