### ISSUE TITLE
https://deken.puredata.info/ feature request, show list of newest uploads to deken 

### ISSUE THREAD

**Issue by abreubacelar** [pure-data/pddp#49]
and related to #48 , would be interesting to have some option in https://deken.puredata.info/ to ask for the newest uploaded things... or maybe an auto generated page on puredata.info directly? this would be good for example to catch the most recent plugins and libraries available 

as it is right now, if i go to https://puredata.info/downloads , the most recent library listed is jmmmp 0.61 (from 26/05/2021) but i know that cyclone and else for example had other releases more recently, and by the way else doesn't even shows in the download category, so i suppose this has to be manually updated... it is possible to get a list with the most recent uploads to deken?

**Comment by umlaeute** [comment]
technically https://puredata.info/downloads is not really bound to deken.

- deken shows any downloadable file on the entire https://puredata.info/ that matches the [deken filename pattern](https://github.com/pure-data/deken/tree/master/developer#filename-format) (both v0 and v1)
   - the files can be hosted *anywhere* on the portal, either in the user's home directory (most often) or within `/downloads`
- contrarily `/downloads` is a self-contained software center on the portal that allows for software releases (deken or not)
  - releases that are listed on the https://puredata.info/downloads must be part sub-folders of the `/downloads` folder and contain a lot of meta-data describing the software package in it's entirety

now, ideally `deken` packages would just be hosted on https://puredata.info/downloads rather than the users' home directories (https://puredata.info/Members).
the reason why this is not happening is that
- uploading to `/downloads` is a much more convoluted process (you have to follow a strict filesystem pattern and provide more metadata)
- it cannot be automated in a simple (script-ready) way (you can do ordinary file uploads (e.g. to `/Members`) via WebDAV, which is what the `deken` cmdline tool uses for uploading; however, due to the metadata required, you cannot do that within the `/downloads` software center)

so the reason why it is like it is is technical.

>  it is possible to get a list with the most recent uploads to deken?

no, not for `/downloads`

things are different for https://deken.puredata.info/
if you think this is worth it, please file a feature request at https://git.iem.at/zmoelnig/deken-server/, ideally with mockups an

**Comment by porres** [comment]
> it is possible to get a list with the most recent uploads to deken

if you click 'show all' in deken, that's what happens, right?

**Comment by porres** [comment]
> right?

nope, but this could be some sort of parameter we could have for displaying the search results, right? Like, alphabetically or considering when it was uploaded, and also something we could have in https://deken.puredata.info/

**Comment by abreubacelar** [comment]
ok, I dropped the puredata.info part from the title. For my use case(1), I discovered that i can parse https://deken.puredata.info/search.json to get info on the libraries, and from there I can sort the libraries by timestamp (thanks Iohannes for the hint of json on the pd-list)

It would be useful to add the feature for the most recent uploads to deken-server if anyone else would want to check for them, but i could also share (when it is complete, i confess that i'm noob at programming, but i am learning) a script that gets that info from the json file... 

since the script will solve the question I will close this (and maybe later edit this comment to point to the script, probably in some attachment to pd-list)

(1): the use case is to have a way to check periodically if there is a new library or plugin or etc, to try to document them in https://pdwiki.miraheze.org/wiki/List_of_Externals , so using a script that gets info from the json file and sort it by timestamp seems to be enough
