### ISSUE TITLE
7.sequencer in DS tutorial can be modernized to use [clone]

### ISSUE THREAD

**Issue by porres** [pure-data/pddp#65]
it uses [route] to several [voice] abstractions instead.

**Comment by porres** [comment]
no, I did not close this one with that commit, my mistake.... I wonder how I can fix this issue and remove the mentioning that the commit fixes it.

help @umlaeute / @Spacechild1  ?

**Comment by umlaeute** [comment]
not sure i can follow.
is it like this?
- you added a line that says `Closes: #65` in 26373e48ff4d8cadaa40de94d5cb001ac0a774e4
- however, that commit is totally unrelated to *this* ticket
- and now you want to get rid of the `Closes` line to not accidentally close this issue once the PR gets merged

is this correct?

there are several ways out here:
- make sure that https://github.com/pure-data/pure-data/pull/1594 actually fixes the issue (even if it is fixed in another commit (which also should have the relevant `Closes:` line), and just ignore that a *wrong* commit also marks this issue as fixed (i've seen much worse and wronger commit messages)
- just ignore the commit message, and make a note to yourself to re-open this issue once the PR got merged (and this issue was wrongly auto-closed)
- fix the commit messages and force push 

otoh, your PR description (which you can always amend) explicitely mentions that it closes https://github.com/pure-data/pddp/issues/65, so it seems that you also went for the 1st option(?)

**Comment by porres** [comment]
While we're at it, I was revising this patch and found some issues. It uses 7 instances of the [voice] abstraction, but not all of them are used. Each instance receives a pointer routed via a [route] object whose argument is "voice number" but it's also actually the color of the pitch array, so we have the values " 0 9 90 900 99 909 990". The thing is that we jus have 4 used colors in the scalars...

Other than that, it's actually meaningless this procedure to route according to a specific color or voice number because they all go to the same copy of the abstraction. It would make sense if [route] would route the pointer to a particular abstraction, so the color could identify a specific "instrument". This is not what happens, though, and one could just use a counter like the "D11" example uses. Well, not actually, as the idea is to use clone and we can just use the 'next' message instead. Moreover, 4 copies would be more than enough.

Hence, in my revision, I'm simplifying the patch a lot. Here's a screenshot, where I'm just using 4 copies of the [voice] abstraction inside [clone] and I'm making use of the 'next' message.

![Screen Shot 2022-03-28 at 15 40 05](https://user-images.githubusercontent.com/5360142/160464860-ccf4954e-f605-4b13-bf32-e41c18903069.png)

Nonetheless, I really really like the original Idea, so I'm keeping the structure in a separate subpatch as a 'proof of concept', explaining how one could use the color field to route to a different "instrument". Here it is.

![Screen Shot 2022-03-28 at 15 42 38](https://user-images.githubusercontent.com/5360142/160465401-916f7d30-cdb8-46ae-9ee0-11f5b009f6f2.png)

I also simplified the [voice] abstraction a bit and included more comments to give more details and explain a bit better how the patch works. The [data-start] abstraction was used only once, so I just made it a subpatch. The [data-array] abstraction was used twice so I kept it, but it was simplified to take just the array name as the argument. I really hope there's no issue regarding these changes as I think they really improve readability. 

Anyway, I'm pushing a new commit that actually deals with this one soon.

**Comment by porres** [comment]
> make sure that https://github.com/pure-data/pure-data/pull/1594 actually fixes the issue (even if it is fixed in another commit (which also should have the relevant Closes: line), and just ignore that a wrong commit also marks this issue as fixed (i've seen much worse and wronger commit messages)

cool, this is what's happening right now :) thanks!
